import Head from "next/head"
import { ConnectWallet } from "@thirdweb-dev/react"
import {
	useAddress,
	useContract,
	useDisconnect,
	useMetamask,
	useMintNFT,
	useNFTs,
	ThirdwebNftMedia,
	useNetwork,
	useNetworkMismatch,
	ChainId,
} from "@thirdweb-dev/react"

export default function Home() {
	const address = useAddress()
	const connectWithMetamask = useMetamask()
	const disconnect = useDisconnect()
	const isWrongNetwork = useNetworkMismatch()
	const [, switchNetwork] = useNetwork()
	const { contract } = useContract("0x80cacf8881F906CAA4322bb45Ccd00c640F4cB1a")
	const { data: nfts, isLoading: isLoadingNfts } = useNFTs(contract)
	const { mutate: mintNFT, isLoading: isMinting } = useMintNFT(contract)

	async function mintAnNft() {
		if (!address) {
			await connectWithMetamask()
			return
		}

		if (isWrongNetwork) {
			await switchNetwork?.(ChainId.Goerli)
			return
		}

		mintNFT({
			metadata: {
				name: "Boruto picture 2",
				image:
					"https://gateway.ipfscdn.io/ipfs/QmUkGDjP2BbCWsqxKuLT5eW5DA5KwhgkVVcdPHaYBgBQk3/90677.png",
			},
			to: address,
		})
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<>
				{address ? (
					<>
						<button type="button" onClick={disconnect}>
							Disconnect wallet
						</button>
						<p>Your address: {address}</p>
						{!isLoadingNfts ? (
							<>
								{nfts?.map((nft) => {
									return (
										<div key={nft.metadata.id.toString()}>
											<ThirdwebNftMedia metadata={nft.metadata} />
										</div>
									)
								})}
							</>
						) : (
							<>Loading NFTS...</>
						)}
						<button type="button" onClick={mintAnNft}>
							{isMinting ? "Minting..." : "Mint NFT"}
						</button>
					</>
				) : (
					<button type="button" onClick={connectWithMetamask}>
						Connect with Metamask
					</button>
				)}
			</>
		</>
	)
}
